// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed logo.png
var ResourceLogoPngData []byte
var ResourceLogoPng = &fyne.StaticResource{
	StaticName:    "logo.png",
	StaticContent: ResourceLogoPngData,
}
